Repository na4zagin3/satyrographos-repo, pull requests merged in 2021-12, with the labels that each got.

#398 Use Satyrographos 0.0.2.11
  snapshot-develop.opam
  snapshot-stable-0-0-5.opam
  snapshot-stable-0-0-6.opam
Labels: ci

#400 Add new snapshot minor versions
  .github/workflows/ci.yaml
  scripts/take-snapshot
  snapshot-develop--1.opam
  snapshot-stable-0-0-6--1.opam
Labels: ci, snapshot

#402 Fix undefined variable expansion SKIP_OLDEST_DEPS
  ci.sh
Labels: ci

#403 Fix flipped skip conditions
  ci.sh
Labels: ci

#405 Temporarily disable OCaml 4.12
  .github/workflows/ci.yaml
Labels: ci

#409 Revert "Workaround satyrographos bug 287"
  .github/workflows/ci.yaml
Labels: ci

#408 Skip oldest-deps check when opam-0install fails
  .github/workflows/ci.yaml
  ci.sh
Labels: ci

#412 Add back easytable.1.1.1 to the snapshots
  snapshot-develop--1.opam
  snapshot-stable-0-0-6--1.opam
Labels: ci, snapshot

#411 Check if the snapshot is consistent
  .github/workflows/ci.yaml
Labels: ci

#413 Disable order check
  .github/workflows/ci.yaml
Labels: ci

#414 Fix consistent checking logic
  .github/workflows/ci-comment.yaml
  .github/workflows/ci.yaml
Labels: ci

#396 2 packages from abenori/satysfi-colorbox at 0.1.0
  packages/satysfi-colorbox-doc/satysfi-colorbox-doc.0.1.0/opam
  packages/satysfi-colorbox/satysfi-colorbox.0.1.0/opam
Labels: needs maintainer action, ci broken

#395 2 packages from monaqa/slydifi at 0.5.0
  packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.5.0/opam
  packages/satysfi-class-slydifi/satysfi-class-slydifi.0.5.0/opam
Labels: needs maintainer action, ci broken

#417 Fix wrong lower version of satysfi-fonts-inconsolata
  packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam
Labels: fix deps
