Repository na4zagin3/satyrographos-repo, pull requests merged in 2022-05, with the labels that each got.

#447 Workaround OPAM Bug 5132
  ci.sh
Labels: ci

#448 Enable OPAMPRECISETRACKING
  ci.sh
Labels: ci

#449 Test oldest-deps against only SATySFi ecosystem
  ci.sh
Labels: ci

#450 Specify version lowerbound of satysfi-base
  packages/satysfi-azmath/satysfi-azmath.0.0.3/opam
Labels: update dependencies

#454 Fix license of current snapshots
  snapshot-develop--1.opam
  snapshot-develop.opam
  snapshot-stable-0-0-4.opam
  snapshot-stable-0-0-5.opam
  snapshot-stable-0-0-6--1.opam
  snapshot-stable-0-0-6.opam
  snapshot-stable-0-0-7.opam
Labels: fix license

#455 Fix wrong dependencies of satysfi-cancel.0.0.1 and satysfi-class-stjarticle.1.3.2
  packages/satysfi-cancel/satysfi-cancel.0.0.1/opam
  packages/satysfi-class-stjarticle/satysfi-class-stjarticle.1.3.2/opam
Labels: fix deps

#457 Support output for comment
  .github/workflows/ci-comment.yaml
  .github/workflows/ci.yaml
  ci.sh
Labels: ci

#456 Fix license of font packages
  packages/satysfi-fonts-asana-math/satysfi-fonts-asana-math.000.958+1+satysfi0.0.4/opam
  packages/satysfi-fonts-bodoni-star-doc/satysfi-fonts-bodoni-star-doc.2.3+satysfi0.0.5/opam
  packages/satysfi-fonts-bodoni-star/satysfi-fonts-bodoni-star.2.3+satysfi0.0.5/opam
  packages/satysfi-fonts-computer-modern-unicode/satysfi-fonts-computer-modern-unicode.0.7.0+satysfi0.0.4/opam
  packages/satysfi-fonts-cormorant-doc/satysfi-fonts-cormorant-doc.3.601+satysfi0.0.5/opam
  packages/satysfi-fonts-cormorant/satysfi-fonts-cormorant.3.601+satysfi0.0.5/opam
  packages/satysfi-fonts-junicode-doc/satysfi-fonts-junicode-doc.1.0002+satysfi0.0.5/opam
  packages/satysfi-fonts-junicode/satysfi-fonts-junicode.1.0002+satysfi0.0.5/opam
  packages/satysfi-fonts-noto-emoji/satysfi-fonts-noto-emoji.1.05+uh+2/opam
  packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.1.004+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-sans-cjk-jp/satysfi-fonts-noto-sans-cjk-jp.2.001+1+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-sans-cjk-sc/satysfi-fonts-noto-sans-cjk-sc.2.001+1/opam
  packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.000+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-sans/satysfi-fonts-noto-sans.2.001+1+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.1.001+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-serif-cjk-jp/satysfi-fonts-noto-serif-cjk-jp.2.001+1+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.000+satysfi0.0.4/opam
  packages/satysfi-fonts-noto-serif/satysfi-fonts-noto-serif.2.001+1+satysfi0.0.4/opam
  packages/satysfi-fonts-theano-doc/satysfi-fonts-theano-doc.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
  packages/satysfi-fonts-theano/satysfi-fonts-theano.2.0+satysfi0.0.3+satyrograhos0.0.2/opam
Labels: fix license

#410 Revert "Temporarily disable OCaml 4.12"
  .github/workflows/ci.yaml
Labels: ci

#458 Fix dependency declaration of ncsq
  packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.0.1/opam
  packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.1.0/opam
  packages/satysfi-ncsq-doc/satysfi-ncsq-doc.0.2.0/opam
  packages/satysfi-ncsq-doc/satysfi-ncsq-doc.1.0.0/opam
  packages/satysfi-ncsq-doc/satysfi-ncsq-doc.2.0.0/opam
  packages/satysfi-ncsq/satysfi-ncsq.0.0.1/opam
  packages/satysfi-ncsq/satysfi-ncsq.0.1.0/opam
  packages/satysfi-ncsq/satysfi-ncsq.0.2.0/opam
  packages/satysfi-ncsq/satysfi-ncsq.1.0.0/opam
  packages/satysfi-ncsq/satysfi-ncsq.2.0.0/opam
  packages/satysfi-ncsq/satysfi-ncsq.2.1.0/opam
Labels: fix deps

#460 Comment should be posted from ci.sh
  ci.sh
Labels: bug, ci

#459 2 packages from pickoba/satysfi-algorithm at 1.0.0
  packages/satysfi-algorithm-doc/satysfi-algorithm-doc.1.0.0/opam
  packages/satysfi-algorithm/satysfi-algorithm.1.0.0/opam
Labels: new package

#463 Support adding alpha versions of SATySFi
  scripts/add-satysfi
Labels: snapshot

#464 Ignore comment files when pull-number is empty
  .github/workflows/ci-comment.yaml
Labels: bug

#467 Distinguish ci results from different ocaml versions
  .github/workflows/ci-comment.yaml
  .github/workflows/ci.yaml
Labels: ci
